# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = 'fa4fb7d'
__repo_version__ = 'fa4fb7d'
__fingerprint__ = 'fa4fb7d4f99d61dcf1ae168f548992a580840acf'
__dependency_versions__ = {
    'boost': '1.60.lsst1+2',
    'python': 'unknown',
    'boost_regex': '1.60.lsst1+2',
    'base': '14.0-7-g79b6bfd+2',
    'pex_exceptions': '14.0-1-g13ef843+2',
    'numpy': '1.13.1',
    'utils': '14.0-4-gac01bb5+2',
    'eigen': '3.2.5.lsst2-1-g8975fe8',
    'fftw': '3.3.4.lsst2',
    'ndarray': '1.3.0-4-g0cefb59+3',
    'boost_test': '1.60.lsst1+2',
    'pybind11': '2.1.1',
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
