# This file is part of cp_pipe.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from ._configure import *
from .cpBfk import *
from .cpCombine import *
from .cpCrosstalk import *
from .cpCtiSolve import *
from .cpDark import *
from .cpDefects import *
from .cpFilterScan import *
from .cpFlatMeasure import *
from .cpFlatGradients import *
from .cpFringe import *
from .cpLinearitySolve import *
from .cpLinearityNormalize import *
from .cpMonochromaticQEScan import *
from .cpPhotodiodeCorrection import *
from .cpSky import *
from .cpSpectroFlat import *
from .ptc import *
from .utilsEfd import *
from .version import *  # generated by sconsUtils unless you tell it not to

from lsst.ip.isr.deferredCharge import OverscanModel as _OverscanModel
from lsst.ip.isr.deferredCharge import SimpleModel as _SimpleModel
from lsst.ip.isr.deferredCharge import SimulatedModel as _SimulatedModel
from lsst.ip.isr.deferredCharge import SegmentSimulator as _SegmentSimulator
from lsst.ip.isr.deferredCharge import FloatingOutputAmplifier as _FloatingOutputAmplifier

from deprecated.sphinx import deprecated

@deprecated(
    reason="lsst.cp.pipe.OvercsanModel will be moved to lsst.ip.isr.deferredCharge.OverscanModel in v28.0.",
    version="v28.0",
    category=FutureWarning,
)
class OverscanModel(_OverscanModel):
    pass


@deprecated(
    reason="lsst.cp.pipe.SimpleModel will be moved to lsst.ip.isr.deferredCharge.SimpleModel in v28.0.",
    version="v28.0",
    category=FutureWarning,
)
class SimpleModel(_SimpleModel):
    pass


@deprecated(
    reason="lsst.cp.pipe.SimulatedModel will be moved to lsst.ip.isr.deferredCharge.SimulatedModel in v28.0.",
    version="v28.0",
    category=FutureWarning,
)
class SimulatedModel(_SimulatedModel):
    pass


@deprecated(
    reason="lsst.cp.pipe.SegmentSimulator will be moved to lsst.ip.isr.deferredCharge.SegmentSimulator in v28.0.",
    version="v28.0",
    category=FutureWarning,
)
class SegmentSimulator(_SegmentSimulator):
    pass


@deprecated(
    reason="lsst.cp.pipe.FloatingOutputAmplifier will be moved to lsst.ip.isr.deferredCharge.FloatingOutputAmplifier in v28.0.",
    version="v28.0",
    category=FutureWarning,
)
class FloatingOutputAmplifier(_FloatingOutputAmplifier):
    pass

del deprecated
